package cz.cuni.mff.kyjovsm.ocr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T13:53:47.764+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/", name = "OCR")
@XmlSeeAlso({ObjectFactory.class})
public interface OCR {

    @WebMethod
    @RequestWrapper(localName = "getTaskResult", targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/", className = "cz.cuni.mff.kyjovsm.ocr.GetTaskResult")
    @ResponseWrapper(localName = "getTaskResultResponse", targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/", className = "cz.cuni.mff.kyjovsm.ocr.GetTaskResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cz.cuni.mff.kyjovsm.ocr.TaskResult getTaskResult(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "compute", targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/", className = "cz.cuni.mff.kyjovsm.ocr.Compute")
    @ResponseWrapper(localName = "computeResponse", targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/", className = "cz.cuni.mff.kyjovsm.ocr.ComputeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean compute(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
