package cz.cuni.mff.kyjovsm.ocr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T13:53:47.795+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "OCRService",
                  wsdlLocation = "file:/D:/micha/dev/uni/nswi145/05-cxf/src/main/resources/ocr.wsdl",
                  targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/")
public class OCRService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ocr.kyjovsm.mff.cuni.cz/", "OCRService");
    public final static QName OCRPort = new QName("http://ocr.kyjovsm.mff.cuni.cz/", "OCRPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/micha/dev/uni/nswi145/05-cxf/src/main/resources/ocr.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OCRService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/micha/dev/uni/nswi145/05-cxf/src/main/resources/ocr.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OCRService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OCRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OCRService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OCRService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OCRService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OCRService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OCR
     */
    @WebEndpoint(name = "OCRPort")
    public OCR getOCRPort() {
        return super.getPort(OCRPort, OCR.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OCR
     */
    @WebEndpoint(name = "OCRPort")
    public OCR getOCRPort(WebServiceFeature... features) {
        return super.getPort(OCRPort, OCR.class, features);
    }

}
