
package cz.cuni.mff.kyjovsm.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Wed Mar 23 15:28:38 CET 2022
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "computeResponse", namespace = "http://ocr.kyjovsm.mff.cuni.cz/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "computeResponse", namespace = "http://ocr.kyjovsm.mff.cuni.cz/")

public class ComputeResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

