
package cz.cuni.mff.kyjovsm.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Wed Mar 23 15:28:38 CET 2022
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "getTaskResult", namespace = "http://ocr.kyjovsm.mff.cuni.cz/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTaskResult", namespace = "http://ocr.kyjovsm.mff.cuni.cz/")

public class GetTaskResult {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

