
package cz.cuni.mff.kyjovsm.ocr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:16:18.837+01:00
 * Generated source version: 3.5.1
 *
 */
public final class OCR_OCRPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ocr.kyjovsm.mff.cuni.cz/", "OCRService");

    private OCR_OCRPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OCRService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OCRService ss = new OCRService(wsdlURL, SERVICE_NAME);
        OCR port = ss.getOCRPort();

        {
        System.out.println("Invoking getTaskResult...");
        java.lang.String _getTaskResult_arg0 = "";
        cz.cuni.mff.kyjovsm.ocr.TaskResult _getTaskResult__return = port.getTaskResult(_getTaskResult_arg0);
        System.out.println("getTaskResult.result=" + _getTaskResult__return);


        }
        {
        System.out.println("Invoking compute...");
        java.lang.String _compute_arg0 = "";
        java.lang.String _compute_arg1 = "";
        boolean _compute__return = port.compute(_compute_arg0, _compute_arg1);
        System.out.println("compute.result=" + _compute__return);


        }

        System.exit(0);
    }

}
