
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.kyjovsm.ocr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:16:18.914+01:00
 * Generated source version: 3.5.1
 *
 */

@javax.jws.WebService(
                      serviceName = "OCRService",
                      portName = "OCRPort",
                      targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/",
                      wsdlLocation = "file:/home/michalkyjovsky/dev/uni/nswi145/05-cxf/cxf/src/main/resources/ocr.wsdl",
                      endpointInterface = "cz.cuni.mff.kyjovsm.ocr.OCR")

public class OCRPortImpl implements OCR {

    private static final Logger LOG = Logger.getLogger(OCRPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cz.cuni.mff.kyjovsm.ocr.OCR#getTaskResult(java.lang.String arg0)*
     */
    public cz.cuni.mff.kyjovsm.ocr.TaskResult getTaskResult(java.lang.String arg0) {
        LOG.info("Executing operation getTaskResult");
        System.out.println(arg0);
        try {
            cz.cuni.mff.kyjovsm.ocr.TaskResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cz.cuni.mff.kyjovsm.ocr.OCR#compute(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean compute(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation compute");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
