package cz.cuni.mff.kyjovsm.ocr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T19:42:08.735+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(name = "OCR", targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/")
public interface OCR {

    @WebMethod(operationName = "getTaskResult", action = "urn:GetTaskResult")
	public cz.cuni.mff.kyjovsm.ocr.TaskResult getTaskResult(

        java.lang.String arg0
    );

    @WebMethod(operationName = "compute", action = "urn:Compute")
	public boolean compute(

        java.lang.String arg0,
        java.lang.String arg1
    );
}
