
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.kyjovsm;
import cz.cuni.mff.kyjovsm.ocr.OCR;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2022-03-23T15:28:39.368+01:00
 * Generated source version: 2.7.9
 * 
 */
public class OCRClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://ocr.kyjovsm.mff.cuni.cz/", "OCRService");
        QName portName = new QName("http://ocr.kyjovsm.mff.cuni.cz/", "OCRPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/OCRPort"); 
        OCR client = service.getPort(portName,  OCR.class);
        
        // Insert code to invoke methods on the client here

        {
            System.out.println("Invoking getTaskResult...");
            java.lang.String _getTaskResult_arg0 = "";
            cz.cuni.mff.kyjovsm.ocr.TaskResult _getTaskResult__return = client.getTaskResult(_getTaskResult_arg0);
            System.out.println("getTaskResult.result=" + _getTaskResult__return);


        }
        {
            System.out.println("Invoking compute...");
            java.lang.String _compute_arg0 = "";
            java.lang.String _compute_arg1 = "";
            boolean _compute__return = client.compute(_compute_arg0, _compute_arg1);
            System.out.println("compute.result=" + _compute__return);


        }

        System.exit(0);
    }

}