
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.kyjovsm;
import cz.cuni.mff.kyjovsm.ocr.OCR;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2022-03-23T15:28:39.352+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(endpointInterface = "cz.cuni.mff.kyjovsm.ocr.OCR", serviceName = "OCRService")                      
public class OCRImpl implements OCR {

    public cz.cuni.mff.kyjovsm.ocr.TaskResult getTaskResult(java.lang.String arg0) {  
        System.out.println(arg0);    
        try {
            cz.cuni.mff.kyjovsm.ocr.TaskResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }


    public boolean compute(java.lang.String arg0,java.lang.String arg1) {  
        System.out.println(arg0);        System.out.println(arg1);    
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }

}