
package cz.cuni.mff.kyjovsm;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2022-03-23T15:28:39.366+01:00
 * Generated source version: 2.7.9
 * 
 */
 
public class OCRServer{

    protected OCRServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new cz.cuni.mff.kyjovsm.ocr.OCRImpl();
        String address = "http://localhost:9090/OCRPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new OCRServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 