
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.kyjovsm.ocr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T19:42:08.726+01:00
 * Generated source version: 3.5.1
 *
 */

@javax.jws.WebService(
                      serviceName = "OCRService",
                      portName = "OCRPort",
                      targetNamespace = "http://ocr.kyjovsm.mff.cuni.cz/",
                      wsdlLocation = "file:/D:/micha/dev/uni/nswi145/05-lab/src/main/resources/ocr.wsdl",
                      endpointInterface = "cz.cuni.mff.kyjovsm.ocr.OCR")

public class OCRPortImpl implements OCR {

    private static final Logger LOG = Logger.getLogger(OCRPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cz.cuni.mff.kyjovsm.ocr.OCR#getTaskResult(java.lang.String arg0)*
     */
    public cz.cuni.mff.kyjovsm.ocr.TaskResult getTaskResult(java.lang.String arg0) {
        LOG.info("Executing operation getTaskResult");
        System.out.println(arg0);
        try {
            cz.cuni.mff.kyjovsm.ocr.TaskResult _return = new cz.cuni.mff.kyjovsm.ocr.TaskResult();
            cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata _returnMetadata = new cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata();
            java.util.List<cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata.Entry> _returnMetadataEntry = new java.util.ArrayList<cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata.Entry>();
            cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata.Entry _returnMetadataEntryVal1 = new cz.cuni.mff.kyjovsm.ocr.TaskResult.Metadata.Entry();
            _returnMetadataEntryVal1.setKey("Key-48909567");
            _returnMetadataEntryVal1.setValue("Value-2073064879");
            _returnMetadataEntry.add(_returnMetadataEntryVal1);
            _returnMetadata.getEntry().addAll(_returnMetadataEntry);
            _return.setMetadata(_returnMetadata);
            cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet _returnResultSet = new cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet();
            java.util.List<cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet.Entry> _returnResultSetEntry = new java.util.ArrayList<cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet.Entry>();
            cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet.Entry _returnResultSetEntryVal1 = new cz.cuni.mff.kyjovsm.ocr.TaskResult.ResultSet.Entry();
            _returnResultSetEntryVal1.setKey("Key-430488833");
            _returnResultSetEntryVal1.setValue("Value431023548");
            _returnResultSetEntry.add(_returnResultSetEntryVal1);
            _returnResultSet.getEntry().addAll(_returnResultSetEntry);
            _return.setResultSet(_returnResultSet);
            _return.setTaskId("TaskId-993084414");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cz.cuni.mff.kyjovsm.ocr.OCR#compute(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean compute(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation compute");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
